# Exemplo de secrets para Streamlit Cloud (defina no painel do Streamlit)
# Obs.: valores aqui são exemplos; NÃO versione credenciais reais.

[general]
project = "matupiri"

[paths]
POLICIES_XLSX = "data/processed/politicas_publicas.xlsx"
DEFESOS_CSV   = "data/processed/defesos.csv"
UCS_CSV       = "data/processed/ucs.csv"
UCS_GEOJSON   = "data/processed/ucs.geojson"
GEO_UFS       = "data/processed/geo/ufs.csv"
GEO_MUN       = "data/processed/geo/municipios.csv"
PROFILE_SCHEMA = "data/docs/profile_schema.json"
KEYWORD_MAP    = "data/docs/keyword_map.json"

[db]
# Caso use arquivo SQLite:
SQLITE_PATH = "pp_platform.db"
# Ou, se migrar para Postgres/CloudSQL:
# DATABASE_URL = "postgresql+psycopg://user:pass@host:5432/dbname"

[feature_flags]
ENABLE_OBSERVATORIO = true
