name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        python-version: [ "3.11" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff mypy pytest pytest-cov openpyxl geopandas pyogrio

      - name: Lint (ruff)
        run: ruff check .

      - name: Type check (mypy)
        run: |
          mypy app --ignore-missing-imports --install-types --non-interactive || true

      - name: Run tests
        env:
          # para os testes apontarem para um caminho temporário, se necessário
          POLICIES_XLSX: data/processed/politicas_publicas.xlsx
        run: |
          pytest -q --maxfail=1 --disable-warnings --cov=app --cov-report=xml

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
